/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "bufgdjhyftyzcvveaniy"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ1Zmdkamh5ZnR5emN2dmVhbml5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjYyMTM4NjgsImV4cCI6MjA4MTc4OTg2OH0.Zba-U4Ij2Asr6JtyNKUbC3XB03F-9oO7qqGiPBxo0T0"